server:
    compression:
        enabled: true
        mime-types: application/json
    port: 8080
spring:
    profiles:
        active: 'prod'
## 书信息
demo:
    book:
        name: 《Spring Boot 2.x 核心技术实战 - 上 基础篇》
        writer: 泥瓦匠BYSocket